/**
 * PPK2 codec — pure, transport-free logic for the Nordic Power Profiler Kit II:
 * source-voltage command encoding, GET_META_DATA response parsing, and the
 * streaming sample decoder (raw 4-byte words -> calibrated microamps).
 *
 * Faithful TypeScript port of the `ppk2_api` Python reference implementation
 * (`ppk2_api.py`), including its calibration polynomial and the rolling-average
 * spike filter applied around measurement-range transitions. Unit tests compare
 * this module's output against fixtures generated by the Python original.
 */

import { PPK2_SAMPLE_BYTES, PPK2_VDD_MAX_MV, PPK2_VDD_MIN_MV } from './constants.js';

/** Per-range calibration table (5 measurement ranges, index 0-4). */
export type Ppk2RangeTable = [number, number, number, number, number];

/** Calibration modifiers reported by the PPK2 metadata blob. */
export interface Ppk2Modifiers {
  /** "Calibrated" flag as reported by the device (string, e.g. "0"/"1"), or null. */
  calibrated: string | null;
  /** Hardware revision string, or null. */
  hw: string | null;
  /** "IA" metadata value, or null. */
  ia: string | null;
  r: Ppk2RangeTable;
  gs: Ppk2RangeTable;
  gi: Ppk2RangeTable;
  o: Ppk2RangeTable;
  s: Ppk2RangeTable;
  i: Ppk2RangeTable;
  ug: Ppk2RangeTable;
}

/** Fallback modifiers for an uncalibrated device (matches ppk2_api defaults). */
export const DEFAULT_PPK2_MODIFIERS: Readonly<Ppk2Modifiers> = Object.freeze({
  calibrated: null,
  hw: null,
  ia: null,
  r: [1031.64, 101.65, 10.15, 0.94, 0.043] as Ppk2RangeTable,
  gs: [1, 1, 1, 1, 1] as Ppk2RangeTable,
  gi: [1, 1, 1, 1, 1] as Ppk2RangeTable,
  o: [0, 0, 0, 0, 0] as Ppk2RangeTable,
  s: [0, 0, 0, 0, 0] as Ppk2RangeTable,
  i: [0, 0, 0, 0, 0] as Ppk2RangeTable,
  ug: [1, 1, 1, 1, 1] as Ppk2RangeTable,
});

export function clonePpk2Modifiers(m: Readonly<Ppk2Modifiers>): Ppk2Modifiers {
  return {
    calibrated: m.calibrated,
    hw: m.hw,
    ia: m.ia,
    r: [...m.r],
    gs: [...m.gs],
    gi: [...m.gi],
    o: [...m.o],
    s: [...m.s],
    i: [...m.i],
    ug: [...m.ug],
  };
}

/** Clamp a requested source/input voltage to the regulator's supported span. */
export function clampSourceVoltageMv(mV: number): number {
  return Math.min(PPK2_VDD_MAX_MV, Math.max(PPK2_VDD_MIN_MV, Math.trunc(mV)));
}

/**
 * Encode a source voltage as the two REGULATOR_SET argument bytes.
 * 800 mV (the minimum) encodes as [3, 32]; values scale linearly from there.
 */
export function convertSourceVoltage(mV: number): [number, number] {
  const clamped = clampSourceVoltageMv(mV);
  const diffToBaseline = clamped - PPK2_VDD_MIN_MV + 32;
  const b1 = 3 + Math.trunc(diffToBaseline / 256);
  const b2 = diffToBaseline % 256;
  return [b1, b2];
}

const INDEXED_MODIFIER_KEYS = ['r', 'gs', 'gi', 'o', 's', 'i', 'ug'] as const;

/**
 * Parse the ASCII GET_META_DATA response ("Key: value" lines terminated by
 * "END") into a modifiers table, starting from the uncalibrated defaults.
 *
 * Quirk preserved from ppk2_api: an `R<n>` value of exactly 0 is ignored
 * (some PPK2 units report broken zero calibration for R) so the default
 * resistor value survives. Divergence from Python: a malformed line is
 * skipped instead of aborting the whole parse.
 */
export function parsePpk2Metadata(text: string): Ppk2Modifiers {
  const modifiers = clonePpk2Modifiers(DEFAULT_PPK2_MODIFIERS);

  for (const rawLine of text.split('\n')) {
    const sep = rawLine.indexOf(': ');
    if (sep <= 0) continue;
    const key = rawLine.slice(0, sep).trim();
    const value = rawLine.slice(sep + 2).trim();

    if (key === 'Calibrated') {
      modifiers.calibrated = value;
      continue;
    }
    if (key === 'HW') {
      modifiers.hw = value;
      continue;
    }
    if (key === 'IA') {
      modifiers.ia = value;
      continue;
    }

    for (const mod of INDEXED_MODIFIER_KEYS) {
      const upper = mod.toUpperCase();
      if (!key.startsWith(upper)) continue;
      const index = Number(key.slice(upper.length));
      if (!Number.isInteger(index) || index < 0 || index > 4 || key !== `${upper}${index}`) {
        continue;
      }
      const parsed = Number.parseFloat(value);
      if (!Number.isFinite(parsed)) continue;
      if (mod === 'r' && parsed === 0) continue; // broken zero calibration -> keep default
      modifiers[mod][index] = parsed;
      break;
    }
  }

  return modifiers;
}

/** One decoded batch of measurement samples. */
export interface Ppk2SampleBatch {
  /** Calibrated current samples in microamps. */
  microAmps: Float64Array;
  /** Digital logic-port byte per sample (bits 24-31 of the raw word). */
  logic: Uint8Array;
}

const ADC_MULT = 1.8 / 163840;
const SPIKE_FILTER_ALPHA = 0.18;
const SPIKE_FILTER_ALPHA5 = 0.06;
const SPIKE_FILTER_SAMPLES = 3;

/**
 * Streaming decoder for the PPK2 measurement stream.
 *
 * Feed it arbitrary chunks of the serial byte stream; it decodes every
 * complete 4-byte little-endian word into a calibrated microamp value and
 * carries any trailing partial word over to the next feed() call. Output is
 * invariant to how the stream is split into chunks.
 *
 * Deliberate divergence from the Python reference: ppk2_api's get_samples()
 * zero-pads and decodes a leading partial word when fewer than 4 bytes are
 * available; this port only ever decodes complete words.
 */
export class Ppk2SampleDecoder {
  private modifiers: Ppk2Modifiers;
  private sourceVoltageMv: number;

  private remainder = new Uint8Array(0);

  // Spike-filter state (mirrors ppk2_api.get_adc_result).
  private rollingAvg: number | null = null;
  private rollingAvg4: number | null = null;
  private prevRange: number | null = null;
  private consecutiveRangeSamples = 0;
  private afterSpike = 0;

  constructor(modifiers: Readonly<Ppk2Modifiers>, sourceVoltageMv: number) {
    this.modifiers = clonePpk2Modifiers(modifiers);
    this.sourceVoltageMv = sourceVoltageMv;
  }

  setModifiers(modifiers: Readonly<Ppk2Modifiers>): void {
    this.modifiers = clonePpk2Modifiers(modifiers);
  }

  setSourceVoltage(mV: number): void {
    this.sourceVoltageMv = mV;
  }

  /** Clear the partial-word remainder and all spike-filter state. */
  reset(): void {
    this.remainder = new Uint8Array(0);
    this.rollingAvg = null;
    this.rollingAvg4 = null;
    this.prevRange = null;
    this.consecutiveRangeSamples = 0;
    this.afterSpike = 0;
  }

  /** Decode a chunk of the serial stream into calibrated samples. */
  feed(chunk: Uint8Array): Ppk2SampleBatch {
    let buf: Uint8Array;
    if (this.remainder.length > 0) {
      buf = new Uint8Array(this.remainder.length + chunk.length);
      buf.set(this.remainder, 0);
      buf.set(chunk, this.remainder.length);
    } else {
      buf = chunk;
    }

    const wordCount = Math.floor(buf.length / PPK2_SAMPLE_BYTES);
    const microAmps = new Float64Array(wordCount);
    const logic = new Uint8Array(wordCount);

    const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    for (let w = 0; w < wordCount; w++) {
      const word = view.getUint32(w * PPK2_SAMPLE_BYTES, true);
      const adcResult = (word & 0x3fff) * 4;
      const range = Math.min((word >>> 14) & 0x7, 4);
      microAmps[w] = this.calibrate(range, adcResult) * 1e6;
      logic[w] = (word >>> 24) & 0xff;
    }

    const consumed = wordCount * PPK2_SAMPLE_BYTES;
    // slice() (not subarray) so the remainder does not pin the incoming chunk.
    this.remainder = buf.slice(consumed);

    return { microAmps, logic };
  }

  /**
   * Calibration polynomial + spike filter, ported verbatim from
   * ppk2_api.get_adc_result. Returns amps (not microamps).
   */
  private calibrate(range: number, adcResult: number): number {
    const m = this.modifiers;
    const resultWithoutGain = (adcResult - m.o[range]) * (ADC_MULT / m.r[range]);
    let adc =
      m.ug[range] *
      (resultWithoutGain * (m.gs[range] * resultWithoutGain + m.gi[range]) +
        (m.s[range] * (this.sourceVoltageMv / 1000) + m.i[range]));

    const prevRollingAvg = this.rollingAvg;
    const prevRollingAvg4 = this.rollingAvg4;

    this.rollingAvg =
      this.rollingAvg === null
        ? adc
        : SPIKE_FILTER_ALPHA * adc + (1 - SPIKE_FILTER_ALPHA) * this.rollingAvg;
    this.rollingAvg4 =
      this.rollingAvg4 === null
        ? adc
        : SPIKE_FILTER_ALPHA5 * adc + (1 - SPIKE_FILTER_ALPHA5) * this.rollingAvg4;

    if (this.prevRange === null) {
      this.prevRange = range;
    }

    if (this.prevRange !== range || this.afterSpike > 0) {
      if (this.prevRange !== range) {
        this.consecutiveRangeSamples = 0;
        this.afterSpike = SPIKE_FILTER_SAMPLES;
      } else {
        this.consecutiveRangeSamples += 1;
      }

      if (range === 4) {
        if (this.consecutiveRangeSamples < 2) {
          this.rollingAvg = prevRollingAvg;
          this.rollingAvg4 = prevRollingAvg4;
        }
        adc = this.rollingAvg4 as number;
      } else {
        adc = this.rollingAvg as number;
      }

      this.afterSpike -= 1;
    }

    this.prevRange = range;
    return adc;
  }
}

/** Incremental mean/min/max over a stream of sample batches. Bounded memory. */
export class RunningStats {
  count = 0;
  min = Number.POSITIVE_INFINITY;
  max = Number.NEGATIVE_INFINITY;
  private sum = 0;

  add(samples: ArrayLike<number>): void {
    for (let i = 0; i < samples.length; i++) {
      const v = samples[i];
      this.sum += v;
      if (v < this.min) this.min = v;
      if (v > this.max) this.max = v;
    }
    this.count += samples.length;
  }

  get mean(): number {
    return this.count === 0 ? NaN : this.sum / this.count;
  }

  reset(): void {
    this.count = 0;
    this.sum = 0;
    this.min = Number.POSITIVE_INFINITY;
    this.max = Number.NEGATIVE_INFINITY;
  }
}

/** One downsampled bin. */
export interface MinMaxBin {
  min: number;
  max: number;
  mean: number;
}

/**
 * Peak-preserving downsampler: folds a 100 kS/s stream into fixed-size bins
 * of {min, max, mean}, optionally keeping only the most recent `maxBins`
 * (ring buffer) so live-view memory stays bounded.
 */
export class MinMaxDownsampler {
  readonly binSize: number;
  private readonly maxBins: number;

  private bins: MinMaxBin[] = [];
  private head = 0; // ring start index once capped
  private curCount = 0;
  private curSum = 0;
  private curMin = Number.POSITIVE_INFINITY;
  private curMax = Number.NEGATIVE_INFINITY;
  private total = 0;

  constructor(binSize: number, maxBins = Number.POSITIVE_INFINITY) {
    if (!Number.isInteger(binSize) || binSize < 1) {
      throw new Error('binSize must be a positive integer');
    }
    this.binSize = binSize;
    this.maxBins = maxBins;
  }

  /** Total number of samples pushed (including those in the partial bin). */
  get totalSamples(): number {
    return this.total;
  }

  get binCount(): number {
    return this.bins.length;
  }

  push(samples: ArrayLike<number>): void {
    for (let i = 0; i < samples.length; i++) {
      const v = samples[i];
      this.curSum += v;
      if (v < this.curMin) this.curMin = v;
      if (v > this.curMax) this.curMax = v;
      this.curCount += 1;
      if (this.curCount === this.binSize) this.commitBin();
    }
    this.total += samples.length;
  }

  private commitBin(): void {
    const bin: MinMaxBin = {
      min: this.curMin,
      max: this.curMax,
      mean: this.curSum / this.curCount,
    };
    if (this.bins.length < this.maxBins) {
      this.bins.push(bin);
    } else {
      this.bins[this.head] = bin;
      this.head = (this.head + 1) % this.bins.length;
    }
    this.curCount = 0;
    this.curSum = 0;
    this.curMin = Number.POSITIVE_INFINITY;
    this.curMax = Number.NEGATIVE_INFINITY;
  }

  /** Completed bins in chronological order (excludes the partial bin). */
  snapshot(): MinMaxBin[] {
    if (this.head === 0) return this.bins.slice();
    return [...this.bins.slice(this.head), ...this.bins.slice(0, this.head)];
  }

  reset(): void {
    this.bins = [];
    this.head = 0;
    this.curCount = 0;
    this.curSum = 0;
    this.curMin = Number.POSITIVE_INFINITY;
    this.curMax = Number.NEGATIVE_INFINITY;
    this.total = 0;
  }
}
